# Basic appveyor configuration : CodeCakeBuilder does the job.
version: build{build}
branches:
  only:
  - master
  - develop
install:
- ps: CodeCakeBuilder\Bootstrap.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off